do not dedupe alternate schema source expresions
github/secure_headers pull request #478
Opened 2022-04-01 11:03 UTC by keithamus

## All PRs:

* [x] Has tests
* [x] ~~Documentation updated~~ N/A

## Adding a new header

Generally, adding a new header is always OK.

* Is the header supported by any user agent? If so, which? N/A
* What does it do? N/A
* What are the valid values for the header? N/A
* Where does the specification live? N/A

## Adding a new CSP directive

* Is the directive supported by any user agent? If so, which? N/A
* What does it do? N/A
* What are the valid values for the directive? N/A

This correct a bug in the `dedup_source_list` function, which causes sources with different protocols to be removed, which breaks possible CSP as headers as the spec only allows for _current protocol_ for schemaless source expressions.

Consider the following `connect-src: *.example.com wss://*.example.com`. This effectively allows for http and websocket connections. The current version of `secure_headers` will minify this to be `connect-src: *.example.com` which only allows for http connections, _disallowing websocket connections_.

The fix here is to check that the schemes match for wildcard sources, using `URI(source).scheme`. For a scheme-less URI like `*.example.com`, the URI will come back with a `scheme` of `nil`, which is fine. There is a step before `dedup_source_list` which strips known schemes like `http`/`https`.

2022-04-01 13:42 UTC, JackMc requested changes
Hey! Thanks for the contribution. I'm unable to reproduce this behaviour. I set up a standard Rails 7 app with a scaffolded resource named `posts` and added the following SecureHeaders initializer:

```ruby
SecureHeaders::Configuration.default do |config|
  config.csp = {
    default_src: %w(* 'unsafe-inline' blob:),
    script_src: %w('self' blob: 'unsafe-inline' data:),
    connect_src: %w('self' *.example.com wss://*.example.com),
  }
end
```

And the following inline script in the resources #index page:

```html
<script>
  fetch('https://example.com');
</script>

<script>
  webSocket = new WebSocket('wss://example.com');
</script>
```

The CSP returned from Secure Headers appears to be:
```http
Content-Security-Policy: default-src * 'unsafe-inline' blob:; block-all-mixed-content; connect-src 'self' *.example.com wss://*.example.com; script-src 'self' blob: 'unsafe-inline' data:
```

Copying the test from `spec/lib/secure_headers/headers/content_security_policy_spec.rb` to `master` passes. Could you provide a failing test case? Happy to hop on a call and discuss if that's easier!

2022-04-01 13:42 UTC, JackMc commented on lib/secure_headers/headers/content_security_policy.rb
> +            wild_sources.any? { |pattern| URI(pattern).scheme == URI(source).scheme && File.fnmatch(pattern, source) }
For large fields, this could result in the source URL being parsed a lot. Would it make sense to precompute the source scheme in the prior loop?

2022-04-01 14:00 UTC, keithamus commented
Thanks for discussing over Slack @JackMc! I've addressed both the badly written test and the precomputation of schemes.

2022-04-01 14:03 UTC, JackMc approved these changes

2022-06-02 15:05 UTC, JackMc commented
I don't see any problem with it!

2022-06-02 15:48 UTC, srt32 commented
I don't have merge access. Could you click the button?

2022-06-15 15:03 UTC, merged