Lowercase headers
github/secure_headers pull request #533
Opened 2024-10-30 22:15 UTC by arashnd

## All PRs:

* [X] Has tests
* [X] Documentation updated

## Adding a new header

Generally, adding a new header is always OK.

* Is the header supported by any user agent? If so, which?
* What does it do?
* What are the valid values for the header?
* Where does the specification live?

## Adding a new CSP directive

* Is the directive supported by any user agent? If so, which?
* What does it do?
* What are the valid values for the directive?

---

Rack 3 `Response header keys can no longer include uppercase characters.`
https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#rack-3-upgrade-guide

Rack Lint error out when using `secure_headers` because its adding headers with uppercase
```
Rack::Lint::LintError: uppercase character in header name: X-Frame-Options (Rack::Lint::LintError)
```

2024-12-06 01:37 UTC, rzhade3 requested changes
Thanks for this PR! This is a great change. Couple changes suggested below after which we can merge this PR in:

2024-12-06 01:37 UTC, rzhade3 commented on CHANGELOG.md
> -- Updates `Referrer-Policy` header to support multiple policy values
We shouldn't retroactively changed the changelog here; it'll be difficult for folks to understand the timeline of changes. Instead, let's add a new release version that states that it lower cases all header keys.

2024-12-06 01:37 UTC, rzhade3 commented on README.md
> +* `block_all_mixed_content` - this value is deprecated in favor of `upgrade_insecure_requests`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/content-security-policy/block-all-mixed-c
```suggestion
* `block_all_mixed_content` - this value is deprecated in favor of `upgrade_insecure_requests`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content for more information.
```

Over aggressive Cmd+F here, the actual URL here uses capitalization.

2024-12-06 01:37 UTC, rzhade3 commented on README.md
>  X-Content-Type-Options: nosniff
```suggestion
x-content-type-options: nosniff
```

2024-12-06 01:37 UTC, rzhade3 commented on README.md
>  X-Frame-Options: sameorigin
```suggestion
x-frame-options: sameorigin
```

2024-12-06 01:37 UTC, rzhade3 commented on README.md
>  X-Xss-Protection: 0
```suggestion
x-xss-protection: 0
```

2024-12-06 01:37 UTC, rzhade3 commented on lib/secure_headers/railtie.rb
>        conflicting_headers = ["X-Frame-Options", "X-XSS-Protection",
```suggestion
      conflicting_headers = ["x-frame-options", "x-xss-protection",
```

2024-12-06 01:37 UTC, rzhade3 commented on lib/secure_headers/railtie.rb
> +                             "X-Content-Type-Options", "strict-transport-security",
```suggestion
                             "x-content-type-options", "strict-transport-security",
```

2024-12-06 01:37 UTC, rzhade3 commented on lib/secure_headers/railtie.rb
> +                             "Public-Key-Pins", "Public-Key-Pins-Report-Only", "referrer-policy"]
```suggestion
                             "public-key-pins", "public-key-pins-report-only", "referrer-policy"]
```

2024-12-06 04:25 UTC, rzhade3 commented on CHANGELOG.md
> -- Updates `Referrer-Policy` header to support multiple policy values
Addressed in https://github.com/github/secure_headers/pull/533/commits/8c5119668de47e00576908c879fa66a8fb41b9fa

2024-12-06 06:05 UTC, arashnd commented
thanks! @rzhade3

2024-12-16 19:06 UTC, KyFaSt approved these changes

2024-12-16 19:11 UTC, merged